#!/bin/bash

sed -i 's/PING 10.0.0.11 (10.0.0.11) 56(84) bytes of data.//' $1
sed -i 's/64 bytes from 10.0.0.11: icmp_seq=1 ttl=64 time=//' $1
sed -i 's/--- 10.0.0.11 ping statistics ---//' $1
sed -i 's/1 packets transmitted, 1 received, 0% packet loss, time 0ms//' $1
sed -i 's/rtt min\/avg\/max\/mdev = //' $1
sed -i 's/.*\/.*\/.*\/.*//' $1
sed -i 's/ ms//' $1

sed -i '/^$/d' $1

awk '{s+=$1; n++} END {if(n) print s/n}' $1